import React from 'react';
// FIX: Import SectionName type.
import type { ResumeData, Template, SectionName } from './types';
import ClassicTemplate from './components/templates/ClassicTemplate';
import ModernTemplate from './components/templates/ModernTemplate';
import CompactTemplate from './components/templates/CompactTemplate';
import ExecutiveTemplate from './components/templates/ExecutiveTemplate';
import TechnicalTemplate from './components/templates/TechnicalTemplate';
import OnyxTemplate from './components/templates/OnyxTemplate';
import CoralTemplate from './components/templates/CoralTemplate';
import ChronologicalTemplate from './components/templates/ChronologicalTemplate';


export const INITIAL_RESUME_DATA: ResumeData = {
  personal: {
    name: 'Your Name',
    email: 'your.email@example.com',
    phone: '123-456-7890',
    linkedin: 'linkedin.com/in/yourprofile',
    portfolio: 'yourportfolio.com',
  },
  summary: 'A brief professional summary about yourself. Highlight your key skills and career goals. This section can be generated by AI.',
  experience: [
    {
      id: crypto.randomUUID(),
      company: 'Awesome Company Inc.',
      role: 'Software Engineer',
      startDate: 'Jan 2022',
      endDate: 'Present',
      description: '- Developed and maintained web applications using React and Node.js.\n- Collaborated with cross-functional teams to deliver high-quality software.\n- Let AI generate more impactful bullet points for you!',
    },
  ],
  education: [
    {
      id: crypto.randomUUID(),
      institution: 'University of Technology',
      degree: 'B.S. in Computer Science',
      startDate: 'Sep 2018',
      endDate: 'Dec 2021',
      gpa: '3.8/4.0',
    },
  ],
  skills: [
    { id: crypto.randomUUID(), name: 'React', category: 'Technical' },
    { id: crypto.randomUUID(), name: 'TypeScript', category: 'Technical' },
    { id: crypto.randomUUID(), name: 'Node.js', category: 'Technical' },
    { id: crypto.randomUUID(), name: 'Teamwork', category: 'Soft' },
    { id: crypto.randomUUID(), name: 'Problem Solving', category: 'Soft' },
  ],
  projects: [
    {
      id: crypto.randomUUID(),
      name: 'AI Resume Builder',
      description: 'A web application to create professional resumes with the help of AI.',
      link: 'github.com/your-repo',
    },
  ],
  certifications: [],
};

export const TEMPLATES: Template[] = [
    { id: 'onyx', name: 'Onyx', component: OnyxTemplate },
    { id: 'coral', name: 'Coral', component: CoralTemplate },
    { id: 'chronological', name: 'Chronological', component: ChronologicalTemplate },
    { id: 'classic', name: 'Classic Professional', component: ClassicTemplate },
    { id: 'modern', name: 'Modern Creative', component: ModernTemplate },
    { id: 'compact', name: 'Compact Minimalist', component: CompactTemplate },
    { id: 'executive', name: 'Executive', component: ExecutiveTemplate },
    { id: 'technical', name: 'Technical', component: TechnicalTemplate },
];

export const INITIAL_SECTION_ORDER: SectionName[] = [
    'summary',
    'experience',
    'education',
    'projects',
    'skills',
    'certifications'
];

// Icons
export const DownloadIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>;
export const UploadIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" /></svg>;
export const SparklesIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M5 2a1 1 0 011 1v1h1a1 1 0 010 2H6v1a1 1 0 01-2 0V6H3a1 1 0 010-2h1V3a1 1 0 011-1zm0 10a1 1 0 011 1v1h1a1 1 0 110 2H6v1a1 1 0 11-2 0v-1H3a1 1 0 110-2h1v-1a1 1 0 011-1zM12 2a1 1 0 01.967.744L14.146 7.2l4.472 1.337a1 1 0 01.53 1.616l-3.35 3.204a1 1 0 00-.28.878l.79 4.394a1 1 0 01-1.45 1.054L12 18.252l-3.955 2.08a1 1 0 01-1.45-1.054l.79-4.394a1 1 0 00-.28.878l-3.35-3.204a1 1 0 01.53-1.616l4.472-1.337L11.033 2.744A1 1 0 0112 2z" clipRule="evenodd" /></svg>;
export const TrashIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>;
export const PlusIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>;
// FIX: Update ChevronDownIcon to accept className prop.
export const ChevronDownIcon = ({ className }: { className?: string }) => <svg xmlns="http://www.w3.org/2000/svg" className={`h-5 w-5 transition-transform ${className ?? ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>;